using System;
using System.Text;

namespace TitanTerminal.Models
{
    public class TestBattlegroup
    {
        public string Battlegroup()
        {
            StringBuilder str = new StringBuilder();
            str.Append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>");
            str.Append("<roster id=\"097c-3e5a-c07d-b49d\" name=\"New Roster\" battleScribeVersion=\"2.03\" gameSystemId=\"975a-00f4-df37-b565\" gameSystemName=\"Adeptus Titanicus 2018\" gameSystemRevision=\"12\" xmlns=\"http://www.battlescribe.net/schema/rosterSchema\">");
            str.Append("  <costs>");
            str.Append("    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"815.0\"/>");
            str.Append("  </costs>");
            str.Append("  <forces>");
            str.Append("    <force id=\"4d0f-c11a-f74b-d438\" name=\"Battlegroup\" entryId=\"d377-9ed7-0d3e-7f70\" catalogueId=\"7c04-d50d-bc70-52f3\" catalogueRevision=\"2\" catalogueName=\"Battlegroup\">");
            str.Append("      <selections>");
            str.Append("        <selection id=\"8b29-4689-acf7-5d38\" name=\"Axiom Battleline Maniple\" entryId=\"d63c-4bb8-d8a9-b777::3ca3-42a8-26bb-5676\" publicationId=\"975a-00f4-pubN65537\" page=\"57\" number=\"1\" type=\"unit\">");
            str.Append("          <rules>");
            str.Append("            <rule id=\"d63c-4bb8-d8a9-b777::a8ff-f985-efc4-9160\" name=\"Might of the Omnissiah\" publicationId=\"975a-00f4-pubN65537\" page=\"57\" hidden=\"false\">");
            str.Append("              <description>If a Titan from this maniple fails a Command check when an order is issued to it in the Issue Orders step of the Strategy phase, orders can still be issued to the rest of the Titans in the maniple. Command checks must still be made for each.</description>");
            str.Append("            </rule>");
            str.Append("          </rules>");
            str.Append("          <selections>");
            str.Append("            <selection id=\"965c-f5ed-9bd3-5872\" name=\"Reaver Titan\" entryId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::9ff1-81bc-203d-620c\" number=\"1\" type=\"model\">");
            str.Append("              <profiles>");
            str.Append("                <profile id=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::7ff1-9cf5-3d51-6ff7\" name=\"Reaver Titan\" hidden=\"false\" typeId=\"f6b0-d09f-1acc-9f3e\" typeName=\"Engine\">");
            str.Append("                  <characteristics>");
            str.Append("                    <characteristic name=\"Speed\" typeId=\"0ef3-ea55-7cd1-d007\">6&quot;/9&quot;</characteristic>");
            str.Append("                    <characteristic name=\"Command\" typeId=\"e94d-33bd-da82-fd4d\">4+</characteristic>");
            str.Append("                    <characteristic name=\"Ballistic Skill\" typeId=\"f14c-a692-0b4a-c510\">3+</characteristic>");
            str.Append("                    <characteristic name=\"Weapon Skill\" typeId=\"935c-7d79-d2fe-dcf8\">4+</characteristic>");
            str.Append("                    <characteristic name=\"Manuever\" typeId=\"d9fc-a9ed-b5ab-e97c\">2/3</characteristic>");
            str.Append("                    <characteristic name=\"Servitor Clades\" typeId=\"a877-9231-f92a-5538\">3</characteristic>");
            str.Append("                    <characteristic name=\"Scale\" typeId=\"5359-4d2b-082b-546a\">8</characteristic>");
            str.Append("                  </characteristics>");
            str.Append("                </profile>");
            str.Append("              </profiles>");
            str.Append("              <selections>");
            str.Append("                <selection id=\"d099-55bb-5e97-7ec0\" name=\"Body\" entryId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::1dcd-1615-5634-3ac7\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <profiles>");
            str.Append("                    <profile id=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::405a-e1d7-49d0-4548\" name=\"Body\" hidden=\"false\" typeId=\"b72e-0b77-ebb5-507d\" typeName=\"Location Table\">");
            str.Append("                      <characteristics>");
            str.Append("                        <characteristic name=\"Direct\" typeId=\"c665-cd89-936b-f2e5\">11-13</characteristic>");
            str.Append("                        <characteristic name=\"Devastating\" typeId=\"d16c-dca6-9e62-f9aa\">14-16</characteristic>");
            str.Append("                        <characteristic name=\"Critical\" typeId=\"d300-246c-10d9-f5b2\">17+</characteristic>");
            str.Append("                      </characteristics>");
            str.Append("                    </profile>");
            str.Append("                  </profiles>");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"979c-7693-c90e-2700\" name=\"⦿⦾⦾⦾⦾⦾⦾(1)\" entryId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::59bd-5186-d156-7809\" entryGroupId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::9ea5-7d31-c03a-5d16\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <profiles>");
            str.Append("                        <profile id=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::6958-b016-77e8-c29b\" name=\"⦿⦾⦾⦾⦾⦾⦾(1)\" hidden=\"false\" typeId=\"e539-8a16-c912-c6c5\" typeName=\"Structure Points\">");
            str.Append("                          <characteristics>");
            str.Append("                            <characteristic name=\"Modifer\" typeId=\"1e91-6224-ebeb-fec2\"/>");
            str.Append("                          </characteristics>");
            str.Append("                        </profile>");
            str.Append("                      </profiles>");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"5b6f-688f-a79c-70ce\" name=\"Head\" entryId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::e785-b175-8850-4890\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <profiles>");
            str.Append("                    <profile id=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::61cc-c41e-f222-a03c\" name=\"Head\" hidden=\"false\" typeId=\"b72e-0b77-ebb5-507d\" typeName=\"Location Table\">");
            str.Append("                      <characteristics>");
            str.Append("                        <characteristic name=\"Direct\" typeId=\"c665-cd89-936b-f2e5\">10-12</characteristic>");
            str.Append("                        <characteristic name=\"Devastating\" typeId=\"d16c-dca6-9e62-f9aa\">13-14</characteristic>");
            str.Append("                        <characteristic name=\"Critical\" typeId=\"d300-246c-10d9-f5b2\">15+</characteristic>");
            str.Append("                      </characteristics>");
            str.Append("                    </profile>");
            str.Append("                  </profiles>");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"e930-22a9-3894-d4c1\" name=\"⦿⦾⦾⦾⦾⦾(1)\" entryId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::7b4b-c92a-0650-3ba2\" entryGroupId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::a049-0f1c-59f2-59f9\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <profiles>");
            str.Append("                        <profile id=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::5238-3213-ec28-3811\" name=\"⦿⦾⦾⦾⦾⦾(1)\" hidden=\"false\" typeId=\"e539-8a16-c912-c6c5\" typeName=\"Structure Points\">");
            str.Append("                          <characteristics>");
            str.Append("                            <characteristic name=\"Modifer\" typeId=\"1e91-6224-ebeb-fec2\"/>");
            str.Append("                          </characteristics>");
            str.Append("                        </profile>");
            str.Append("                      </profiles>");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"0655-e3ad-7a67-2251\" name=\"Legs\" entryId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::de93-8bdc-dd8d-3c91\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <profiles>");
            str.Append("                    <profile id=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::59c9-6941-5ea7-8ecb\" name=\"Legs\" hidden=\"false\" typeId=\"b72e-0b77-ebb5-507d\" typeName=\"Location Table\">");
            str.Append("                      <characteristics>");
            str.Append("                        <characteristic name=\"Direct\" typeId=\"c665-cd89-936b-f2e5\">11-12</characteristic>");
            str.Append("                        <characteristic name=\"Devastating\" typeId=\"d16c-dca6-9e62-f9aa\">13-14</characteristic>");
            str.Append("                        <characteristic name=\"Critical\" typeId=\"d300-246c-10d9-f5b2\">15+</characteristic>");
            str.Append("                      </characteristics>");
            str.Append("                    </profile>");
            str.Append("                  </profiles>");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"2460-ae04-880a-5b95\" name=\"⦿⦾⦾⦾⦾⦾⦾(1)\" entryId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::99b4-2e5d-ce48-cf2a\" entryGroupId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::2736-f5dc-9b2a-8866\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <profiles>");
            str.Append("                        <profile id=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::32e4-fc75-274e-f3ff\" name=\"⦿⦾⦾⦾⦾⦾⦾(1)\" hidden=\"false\" typeId=\"e539-8a16-c912-c6c5\" typeName=\"Structure Points\">");
            str.Append("                          <characteristics>");
            str.Append("                            <characteristic name=\"Modifer\" typeId=\"1e91-6224-ebeb-fec2\"/>");
            str.Append("                          </characteristics>");
            str.Append("                        </profile>");
            str.Append("                      </profiles>");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"39ac-e6fb-d859-27b6\" name=\"Void Shields\" entryId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::ca96-66a7-2466-4553\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"3c17-a21a-ee8a-b37b\" name=\"Void Shield (3+) ⦿⦾⦾⦾⦾\" entryId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::052b-4a86-88ac-055c::e7f3-4f09-8dc2-5b18\" entryGroupId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::71a5-9388-870c-25e1\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"a3ff-f97b-bd31-16ac\" name=\"Plasma Reactor\" entryId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::5c91-fa9e-ab6b-d54c\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"b90f-670b-b4cc-7d33\" name=\"⦿⦾⦾⦾⦾⦾ Green(1)\" entryId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::0822-47ae-0621-86a4\" entryGroupId=\"d63c-4bb8-d8a9-b777::228f-f7a7-d85a-c515::9bdf-f064-c87f-19ce\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("              </selections>");
            str.Append("              <costs>");
            str.Append("                <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"250.0\"/>");
            str.Append("                <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("              </costs>");
            str.Append("              <categories>");
            str.Append("                <category id=\"bf9b-cf7a-8578-9b91\" name=\"Titan\" entryId=\"3f71-3a59-3b75-4ecf\" primary=\"false\"/>");
            str.Append("                <category id=\"d1d2-77ec-0ddf-b6cd\" name=\"ReaverTitan\" entryId=\"d36f-5e44-2150-3428\" primary=\"true\"/>");
            str.Append("              </categories>");
            str.Append("            </selection>");
            str.Append("            <selection id=\"2d5d-b9e5-b2e7-7f60\" name=\"Warlord Titan\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::5122-cb02-8703-ce88\" number=\"1\" type=\"model\">");
            str.Append("              <profiles>");
            str.Append("                <profile id=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::f4bc-0277-b973-df55\" name=\"Warlord Titan\" hidden=\"false\" typeId=\"f6b0-d09f-1acc-9f3e\" typeName=\"Engine\">");
            str.Append("                  <characteristics>");
            str.Append("                    <characteristic name=\"Speed\" typeId=\"0ef3-ea55-7cd1-d007\">4&quot;/6&quot;</characteristic>");
            str.Append("                    <characteristic name=\"Command\" typeId=\"e94d-33bd-da82-fd4d\">3+</characteristic>");
            str.Append("                    <characteristic name=\"Ballistic Skill\" typeId=\"f14c-a692-0b4a-c510\">3+</characteristic>");
            str.Append("                    <characteristic name=\"Weapon Skill\" typeId=\"935c-7d79-d2fe-dcf8\">5+</characteristic>");
            str.Append("                    <characteristic name=\"Manuever\" typeId=\"d9fc-a9ed-b5ab-e97c\">1/2</characteristic>");
            str.Append("                    <characteristic name=\"Servitor Clades\" typeId=\"a877-9231-f92a-5538\">4</characteristic>");
            str.Append("                    <characteristic name=\"Scale\" typeId=\"5359-4d2b-082b-546a\">10</characteristic>");
            str.Append("                  </characteristics>");
            str.Append("                </profile>");
            str.Append("              </profiles>");
            str.Append("              <selections>");
            str.Append("                <selection id=\"33e7-b672-9367-4a12\" name=\"Body\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::b743-b038-6f73-515a\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <profiles>");
            str.Append("                    <profile id=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::d37e-6c0b-a6ec-809a\" name=\"Body\" hidden=\"false\" typeId=\"b72e-0b77-ebb5-507d\" typeName=\"Location Table\">");
            str.Append("                      <characteristics>");
            str.Append("                        <characteristic name=\"Direct\" typeId=\"c665-cd89-936b-f2e5\">12-13</characteristic>");
            str.Append("                        <characteristic name=\"Devastating\" typeId=\"d16c-dca6-9e62-f9aa\">14-15</characteristic>");
            str.Append("                        <characteristic name=\"Critical\" typeId=\"d300-246c-10d9-f5b2\">16+</characteristic>");
            str.Append("                      </characteristics>");
            str.Append("                    </profile>");
            str.Append("                  </profiles>");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"f7c0-49a5-52d7-c899\" name=\"⦿⦾⦾⦾⦾⦾⦾⦾(1)\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::e562-dc55-06b1-9ac7\" entryGroupId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::1b3e-c78e-e4d9-c2ef\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <profiles>");
            str.Append("                        <profile id=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::a323-7e80-9040-bf45\" name=\"⦿⦾⦾⦾⦾⦾⦾⦾(1)\" hidden=\"false\" typeId=\"e539-8a16-c912-c6c5\" typeName=\"Structure Points\">");
            str.Append("                          <characteristics>");
            str.Append("                            <characteristic name=\"Modifer\" typeId=\"1e91-6224-ebeb-fec2\"/>");
            str.Append("                          </characteristics>");
            str.Append("                        </profile>");
            str.Append("                      </profiles>");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"c708-0d8c-071e-062a\" name=\"Head\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::781d-322e-2d97-9cdc\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <profiles>");
            str.Append("                    <profile id=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::4ceb-539b-4d65-8113\" name=\"Head\" hidden=\"false\" typeId=\"b72e-0b77-ebb5-507d\" typeName=\"Location Table\">");
            str.Append("                      <characteristics>");
            str.Append("                        <characteristic name=\"Direct\" typeId=\"c665-cd89-936b-f2e5\">12-13</characteristic>");
            str.Append("                        <characteristic name=\"Devastating\" typeId=\"d16c-dca6-9e62-f9aa\">14-15</characteristic>");
            str.Append("                        <characteristic name=\"Critical\" typeId=\"d300-246c-10d9-f5b2\">17+</characteristic>");
            str.Append("                      </characteristics>");
            str.Append("                    </profile>");
            str.Append("                  </profiles>");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"f419-6144-1fc3-100e\" name=\"⦿⦾⦾⦾⦾⦾⦾(1)\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::47fe-9aed-faad-538e\" entryGroupId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::436f-a436-9bad-a8f3\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <profiles>");
            str.Append("                        <profile id=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::3661-ce55-e831-2aa4\" name=\"⦿⦾⦾⦾⦾⦾⦾(1)\" hidden=\"false\" typeId=\"e539-8a16-c912-c6c5\" typeName=\"Structure Points\">");
            str.Append("                          <characteristics>");
            str.Append("                            <characteristic name=\"Modifer\" typeId=\"1e91-6224-ebeb-fec2\"/>");
            str.Append("                          </characteristics>");
            str.Append("                        </profile>");
            str.Append("                      </profiles>");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"dfa8-f635-dec6-dad2\" name=\"Legs\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::f42b-6054-3a6a-35a0\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <profiles>");
            str.Append("                    <profile id=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::4071-c5a4-5ac7-2b85\" name=\"Legs\" hidden=\"false\" typeId=\"b72e-0b77-ebb5-507d\" typeName=\"Location Table\">");
            str.Append("                      <characteristics>");
            str.Append("                        <characteristic name=\"Direct\" typeId=\"c665-cd89-936b-f2e5\">13-14</characteristic>");
            str.Append("                        <characteristic name=\"Devastating\" typeId=\"d16c-dca6-9e62-f9aa\">15-16</characteristic>");
            str.Append("                        <characteristic name=\"Critical\" typeId=\"d300-246c-10d9-f5b2\">17+</characteristic>");
            str.Append("                      </characteristics>");
            str.Append("                    </profile>");
            str.Append("                  </profiles>");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"26b6-e1b7-521e-473d\" name=\"⦿⦾⦾⦾⦾⦾⦾⦾(1)\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::dbb9-4a9e-75b9-cc09\" entryGroupId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::0e14-822b-8f3c-61e3\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <profiles>");
            str.Append("                        <profile id=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::726b-c370-f63b-e41f\" name=\"⦿⦾⦾⦾⦾⦾⦾⦾(1)\" hidden=\"false\" typeId=\"e539-8a16-c912-c6c5\" typeName=\"Structure Points\">");
            str.Append("                          <characteristics>");
            str.Append("                            <characteristic name=\"Modifer\" typeId=\"1e91-6224-ebeb-fec2\"/>");
            str.Append("                          </characteristics>");
            str.Append("                        </profile>");
            str.Append("                      </profiles>");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"2775-f0e4-5b02-7da5\" name=\"Void Shields\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::a1f0-d644-e812-a244\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"3cdf-c088-2bfa-d555\" name=\"Void Shield (3+) ⦿⦾⦾⦾⦾⦾\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::8e67-15f3-cc86-e5cd::e7f3-4f09-8dc2-5b18\" entryGroupId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::40e8-5105-f3b8-40a9\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"bf25-39ce-5cfb-36e3\" name=\"Plasma Reactor\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::eca7-019e-997f-88e2\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"f02d-8dcf-2aae-c4ad\" name=\"⦿⦾⦾⦾⦾⦾⦾ Green(1)\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::b63f-68eb-52c0-a02f\" entryGroupId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::5be1-a81f-984c-f327\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"c9d8-bc14-9f56-1386\" name=\"Ardex Defensor Cannon\" entryId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::0c27-288f-504a-2110::ebc6-2029-ceb3-f43b\" entryGroupId=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::2c49-32dd-c032-07ff\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <rules>");
            str.Append("                    <rule id=\"d63c-4bb8-d8a9-b777::430c-0860-5432-11ea::0c27-288f-504a-2110::4a77-f09b-b59f-6651\" name=\"Ardex Defensor Cannon\" hidden=\"false\">");
            str.Append("                      <description>When the Titan is activated in the Combat phase, each enemy unit that is within its Front or Rear arc, and within 6&quot;, suffers D3 Strength 5 hits.</description>");
            str.Append("                    </rule>");
            str.Append("                  </rules>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("              </selections>");
            str.Append("              <costs>");
            str.Append("                <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"385.0\"/>");
            str.Append("                <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("              </costs>");
            str.Append("              <categories>");
            str.Append("                <category id=\"4fa1-03ce-f0c7-fac0\" name=\"Titan\" entryId=\"3f71-3a59-3b75-4ecf\" primary=\"false\"/>");
            str.Append("                <category id=\"f899-bab2-d34b-aeb6\" name=\"WarlordTitan\" entryId=\"7103-9316-d4a5-8caa\" primary=\"true\"/>");
            str.Append("              </categories>");
            str.Append("            </selection>");
            str.Append("            <selection id=\"d561-cba6-3973-921c\" name=\"Warhound Titan\" entryId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::3ad7-cd10-8d6e-8c2e\" number=\"1\" type=\"model\">");
            str.Append("              <profiles>");
            str.Append("                <profile id=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::6a50-23dd-224f-f8c3\" name=\"Warhound Titan\" hidden=\"false\" typeId=\"f6b0-d09f-1acc-9f3e\" typeName=\"Engine\">");
            str.Append("                  <characteristics>");
            str.Append("                    <characteristic name=\"Speed\" typeId=\"0ef3-ea55-7cd1-d007\">8&quot;/12&quot;</characteristic>");
            str.Append("                    <characteristic name=\"Command\" typeId=\"e94d-33bd-da82-fd4d\">5+</characteristic>");
            str.Append("                    <characteristic name=\"Ballistic Skill\" typeId=\"f14c-a692-0b4a-c510\">3+</characteristic>");
            str.Append("                    <characteristic name=\"Weapon Skill\" typeId=\"935c-7d79-d2fe-dcf8\">4+</characteristic>");
            str.Append("                    <characteristic name=\"Manuever\" typeId=\"d9fc-a9ed-b5ab-e97c\">3/5</characteristic>");
            str.Append("                    <characteristic name=\"Servitor Clades\" typeId=\"a877-9231-f92a-5538\">2</characteristic>");
            str.Append("                    <characteristic name=\"Scale\" typeId=\"5359-4d2b-082b-546a\">6</characteristic>");
            str.Append("                  </characteristics>");
            str.Append("                </profile>");
            str.Append("              </profiles>");
            str.Append("              <selections>");
            str.Append("                <selection id=\"58f4-0eb5-5f2b-b981\" name=\"Body\" entryId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::2e08-5e77-3e6c-0875\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <profiles>");
            str.Append("                    <profile id=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::9e1c-94e5-7c27-b887\" name=\"Body\" hidden=\"false\" typeId=\"b72e-0b77-ebb5-507d\" typeName=\"Location Table\">");
            str.Append("                      <characteristics>");
            str.Append("                        <characteristic name=\"Direct\" typeId=\"c665-cd89-936b-f2e5\">10-11</characteristic>");
            str.Append("                        <characteristic name=\"Devastating\" typeId=\"d16c-dca6-9e62-f9aa\">12-13</characteristic>");
            str.Append("                        <characteristic name=\"Critical\" typeId=\"d300-246c-10d9-f5b2\">14+</characteristic>");
            str.Append("                      </characteristics>");
            str.Append("                    </profile>");
            str.Append("                  </profiles>");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"f30d-b4e6-3bf9-2dc2\" name=\"⦿⦾⦾⦾⦾⦾(1)\" entryId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::f11f-d438-e068-55b0\" entryGroupId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::6af1-2245-c637-6ede\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <profiles>");
            str.Append("                        <profile id=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::87e2-3a49-fab7-bd12\" name=\"⦿⦾⦾⦾⦾⦾(1)\" hidden=\"false\" typeId=\"e539-8a16-c912-c6c5\" typeName=\"Structure Points\">");
            str.Append("                          <characteristics>");
            str.Append("                            <characteristic name=\"Modifer\" typeId=\"1e91-6224-ebeb-fec2\"/>");
            str.Append("                          </characteristics>");
            str.Append("                        </profile>");
            str.Append("                      </profiles>");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"9090-6b22-ea5b-9392\" name=\"Legs\" entryId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::713c-28fb-4137-ebaa\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <profiles>");
            str.Append("                    <profile id=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::d0bc-768d-a5e6-0860\" name=\"Legs\" hidden=\"false\" typeId=\"b72e-0b77-ebb5-507d\" typeName=\"Location Table\">");
            str.Append("                      <characteristics>");
            str.Append("                        <characteristic name=\"Direct\" typeId=\"c665-cd89-936b-f2e5\">10-12</characteristic>");
            str.Append("                        <characteristic name=\"Devastating\" typeId=\"d16c-dca6-9e62-f9aa\">13-14</characteristic>");
            str.Append("                        <characteristic name=\"Critical\" typeId=\"d300-246c-10d9-f5b2\">15+</characteristic>");
            str.Append("                      </characteristics>");
            str.Append("                    </profile>");
            str.Append("                  </profiles>");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"cd44-a4cf-f546-0725\" name=\"⦿⦾⦾⦾⦾⦾(1)\" entryId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::d606-2a1c-8c9c-5471\" entryGroupId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::9f02-2f8d-abb8-3805\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <profiles>");
            str.Append("                        <profile id=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::5249-a13b-4fe1-91d7\" name=\"⦿⦾⦾⦾⦾⦾(1)\" hidden=\"false\" typeId=\"e539-8a16-c912-c6c5\" typeName=\"Structure Points\">");
            str.Append("                          <characteristics>");
            str.Append("                            <characteristic name=\"Modifer\" typeId=\"1e91-6224-ebeb-fec2\"/>");
            str.Append("                          </characteristics>");
            str.Append("                        </profile>");
            str.Append("                      </profiles>");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"d07a-1d1d-722e-bdaf\" name=\"Head\" entryId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::9ac5-a8f1-414a-71f6\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <profiles>");
            str.Append("                    <profile id=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::7813-edce-26c0-de80\" name=\"Head\" hidden=\"false\" typeId=\"b72e-0b77-ebb5-507d\" typeName=\"Location Table\">");
            str.Append("                      <characteristics>");
            str.Append("                        <characteristic name=\"Direct\" typeId=\"c665-cd89-936b-f2e5\">11-13</characteristic>");
            str.Append("                        <characteristic name=\"Devastating\" typeId=\"d16c-dca6-9e62-f9aa\">14-15</characteristic>");
            str.Append("                        <characteristic name=\"Critical\" typeId=\"d300-246c-10d9-f5b2\">16+</characteristic>");
            str.Append("                      </characteristics>");
            str.Append("                    </profile>");
            str.Append("                  </profiles>");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"cdc4-2104-1393-63aa\" name=\"⦿⦾⦾⦾⦾(1)\" entryId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::3271-618c-4f38-ecc0\" entryGroupId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::54e3-a1e1-034a-f2c2\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <profiles>");
            str.Append("                        <profile id=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::95d4-96cf-8696-9dc0\" name=\"⦿⦾⦾⦾⦾(1)\" hidden=\"false\" typeId=\"e539-8a16-c912-c6c5\" typeName=\"Structure Points\">");
            str.Append("                          <characteristics>");
            str.Append("                            <characteristic name=\"Modifer\" typeId=\"1e91-6224-ebeb-fec2\"/>");
            str.Append("                          </characteristics>");
            str.Append("                        </profile>");
            str.Append("                      </profiles>");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"28fe-18f2-3559-998b\" name=\"Void Shields\" entryId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::33bf-049a-2e61-89c2\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"3bf7-aa9f-c621-ab40\" name=\"Void Shield (3+) ⦿⦾⦾⦾\" entryId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::b3cb-9e84-6181-37dd::e7f3-4f09-8dc2-5b18\" entryGroupId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::74ac-8b96-f42c-3a28\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("                <selection id=\"1794-fad1-e321-b086\" name=\"Plasma Reactor\" entryId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::e9f6-5f0a-f3a7-456b\" number=\"1\" type=\"upgrade\">");
            str.Append("                  <selections>");
            str.Append("                    <selection id=\"fc2a-56c9-752b-6ab1\" name=\"⦿⦾⦾⦾⦾ Green(1)\" entryId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::796b-1378-14f8-3eb3\" entryGroupId=\"d63c-4bb8-d8a9-b777::6922-4409-37e6-3201::a729-d6f9-299f-a129\" number=\"1\" type=\"upgrade\">");
            str.Append("                      <costs>");
            str.Append("                        <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                        <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                      </costs>");
            str.Append("                    </selection>");
            str.Append("                  </selections>");
            str.Append("                  <costs>");
            str.Append("                    <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("                    <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                  </costs>");
            str.Append("                </selection>");
            str.Append("              </selections>");
            str.Append("              <costs>");
            str.Append("                <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"180.0\"/>");
            str.Append("                <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("              </costs>");
            str.Append("              <categories>");
            str.Append("                <category id=\"70ba-0523-3f25-bb38\" name=\"Titan\" entryId=\"3f71-3a59-3b75-4ecf\" primary=\"false\"/>");
            str.Append("                <category id=\"c5d0-a0e7-d702-4fb9\" name=\"WarhoundTitan\" entryId=\"223f-6e71-9e4f-939e\" primary=\"true\"/>");
            str.Append("              </categories>");
            str.Append("            </selection>");
            str.Append("            <selection id=\"2f80-d2e2-0a0e-86c2\" name=\"Titan Legion\" entryId=\"d63c-4bb8-d8a9-b777::2dc6-c52e-3efc-5e21::6202-19dc-f26f-9b64\" number=\"1\" type=\"upgrade\">");
            str.Append("              <costs>");
            str.Append("                <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("                <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("              </costs>");
            str.Append("              <categories>");
            str.Append("                <category id=\"8ead-0c15-2425-fc45\" name=\"Titan Legion\" entryId=\"d204-9898-0ffb-02f4\" primary=\"true\"/>");
            str.Append("              </categories>");
            str.Append("            </selection>");
            str.Append("          </selections>");
            str.Append("          <costs>");
            str.Append("            <cost name=\" Points\" typeId=\"a731-e220-2d8a-41bf\" value=\"0.0\"/>");
            str.Append("            <cost name=\" Stratagem Points\" typeId=\"efbf-52f7-fd08-f329\" value=\"0.0\"/>");
            str.Append("          </costs>");
            str.Append("          <categories>");
            str.Append("            <category id=\"98d7-a084-ac5b-028b\" name=\"Maniple\" entryId=\"6982-2d18-55cb-61e5\" primary=\"true\"/>");
            str.Append("          </categories>");
            str.Append("        </selection>");
            str.Append("      </selections>");
            str.Append("      <publications>");
            str.Append("        <publication id=\"975a-00f4-pubN65537\" name=\"Adeptus Titanicus 2018\"/>");
            str.Append("        <publication id=\"975a-00f4-pubN89746\" name=\"Doom Of Molech\"/>");
            str.Append("        <publication id=\"25e8-c9ce-9330-c53b\" name=\"Titandeath Errata v1.0\"/>");
            str.Append("        <publication id=\"7c04-d50d-pubN65537\" name=\"Adeptus Titanicus 2018\"/>");
            str.Append("        <publication id=\"975a-00f4-pubN89033\" name=\"White Dwarf: Feb 2019\"/>");
            str.Append("        <publication id=\"975a-00f4-pubN87630\" name=\"Titandeath\"/>");
            str.Append("        <publication id=\"7236-e1d8-c886-f5fd\" name=\"Adeptus Titanicus 2018 Errata v1.0\"/>");
            str.Append("      </publications>");
            str.Append("      <categories>");
            str.Append("        <category id=\"0bb8-3307-6e15-5653\" name=\"Uncategorised\" entryId=\"(No Category)\" primary=\"false\"/>");
            str.Append("        <category id=\"d2c2-1940-1191-4704\" name=\"Maniple\" entryId=\"6982-2d18-55cb-61e5\" primary=\"false\"/>");
            str.Append("        <category id=\"6664-6420-5532-337f\" name=\"Titan\" entryId=\"3f71-3a59-3b75-4ecf\" primary=\"false\"/>");
            str.Append("        <category id=\"3746-8126-9fc2-007a\" name=\"Banner\" entryId=\"917a-77ef-30e4-b812\" primary=\"false\">");
            str.Append("          <rules>");
            str.Append("            <rule id=\"59fb-73c8-478f-68c9\" name=\"Banner\" publicationId=\"975a-00f4-pubN65537\" hidden=\"false\">");
            str.Append("              <description>Composition of a Banner");
            str.Append("A Banner is made up of a number of Knights acting as a single unit. The reverse of a Banner&apos;s Command Terminal describes its exact composition, along with any options. When a Banner is activated, all of the Knights within it act; individual Knights cannot be activated.");
            str.Append("");
            str.Append("Banners in the Movement Phase");
            str.Append("When a Banner is activated in the Movement phase, each Knight can move up to the Banner&apos;s Speed characteristic in inches. Knights are considered to have a 360° Front arc, and can make");
            str.Append("as many turns as they wish as they move. When the Banner has finished moving, each must be within 3&quot; of another Knight in the Banner - Knight Banners operate in much closer proximity than Titan Squadrons, especially when facing larger war engines. If any of the Knights are outside of this range, the Banner is Shaken - see page 47.");
            str.Append("");
            str.Append("Banners in the Combat Phase");
            str.Append("When a Banner is activated in the Combat phase, it follows the Combat Sequence as if it were a Titan. Instead of attacking with each Knight individually, make an attack with each different weapon in tum. For each weapon, multiply the Dice characteristic by the number of Knights in the Banner that are equipped with that weapon, and which are within range and line of sight of the target. For example,ifa Banner has two Knights armed with rapid fire battle cannon (Dice 2) and one Knight armed with a thermal cannon (Dicer),it would roll four dice when attacking with the battle cannon and one dice when attacking with the thermal cannon.IfsomeKnightsarewithin2&quot; ofthetargetandothersare further away, roll using Ballistic Skill for those that are further, and Weapon Skill for those that are within 2&quot;.");
            str.Append("");
            str.Append("When determining line of sight for a Banner, Knights within the Banner do not block the view of others. Also, remember that Knights have a 360° Front arc,so their weapons can fire in any direction. All of the weapons in a Banner must be fired at the same target, unless the Banner has Split Fire orders, at which point each weapon can be directed at a different target.");
            str.Append("");
            str.Append("Banners cannot make Smash Attacks.");
            str.Append("");
            str.Append("ATTACKING BANNERS. When attacking a Banner, pick a single Knight in the Banner to be the target of the attack. This model is used for purposes ofrange,line ofsight and so on. However, any damage that is caused is applied to the Banner as a whole. As Banners");
            str.Append("do not have Side or Rear arcs, these do not cause modifiers to the Damage roll.");
            str.Append("");
            str.Append("ION SHIELDS. When fighting in a Banner, Knights align their Ion shields, granting them greater protection as a group than individually. Ion shields are different to void shields;ifa rule refers specifically to void shields, it does not affect ion shields, but ifit refers to Shield saves, it will affect both. Note that, unlike void shields, ion shields can be used against attacks that originate from within 2&quot;.");
            str.Append("If a Banner is hit by a shooting attack, hits are resolved (at Step 5 of the Combat Sequence) as follows:");
            str.Append("• Target&apos;s controlling player makes Ion Shield saves.");
            str.Append("• The attacking player makes Armour rolls for any remaining hits.");
            str.Append("To make an Ion Shield save, look up the Ion Shield level on the Banner&apos;s Command Terminal, which varies depending on the number of Knights currently in the Banner and the Strength of the attack. Then roll a D6 for each hit that was scored. For each dice that equals or beats the Ion Shield level, the hit is discarded. Then for each remaining hit, the attacking player makes an Armour roll as described on page 34.");
            str.Append("");
            str.Append("DAMAGING BANNERS. Direct Hits, Devastating Hits and Critical Hits affect Banners differently to Titans, as follows:");
            str.Append("");
            str.Append("Direct Hit: When a Banner suffers a Direct Hit,it loses a Structure point. If it has no Structure points left to lose, one Knight in the Banner is desttoyed instead.");
            str.Append("");
            str.Append("Devastating Hit: When a Banner suffers a Devastating Hit, it loses two Structure points. If the Banner has one Structure point or no Structure points left when it suffers a Devastating Hit, one Knight in the Banner is destroyed instead.");
            str.Append("");
            str.Append("Critical Hit: When a Banner suffers a Critical Hit, it loses two Structure points, then one Knight in the Banner is destroyed.");
            str.Append("If the Banner has one Structure point or no Structure points j left when it suffers a Critical Hit, two Knights in the Banner are destroyed instead.");
            str.Append("");
            str.Append("When a Knight is destroyed, the controlling player chooses one model to remove. The Banner&apos;s Structure Points marker is then immediately reset to the first hole of the track. If a Targeted Attack destroys a Knight, the attacking player can choose which model to remove instead of the controlling player.");
            str.Append("");
            str.Append("BLAST MARKERS, FLAME TEMPLATES AND AREA EFFECTS. When a Banner is hit by a Blast marker or Flame template, total the number of hits scored on the models in the Banner, then apply that many hits to the Banner as a whole. This also applies to attack~with an area effect - catastrophic reactor overloads, environmental effects and so on.");
            str.Append("");
            str.Append("Shaken Banners");
            str.Append("Each time a Knight is removed from a Banner, the Banner must make a Command check. If it is failed, the Banner is Shaken. It immediately loses any orders and an Order dice showing the Shutdown symbol is placed on its Command Terminal to show that it is Shaken. Shaken Banners subtract 3&quot; from their Speed and will suffer a -1 modifier to all Hit rolls.");
            str.Append("When the Banner is activated in the Issue Orders step of the next Strategy phase, make a Command roll for the Shaken Banner. If it is passed, remove the dice. Otherwise, it stays where it is. In either case, the Banner cannot be issued orders.");
            str.Append("");
            str.Append("</description>");
            str.Append("            </rule>");
            str.Append("          </rules>");
            str.Append("        </category>");
            str.Append("        <category id=\"9fc8-5e81-fdf3-9aca\" name=\"Stratagem\" entryId=\"b539-a35c-fe3f-9c34\" primary=\"false\"/>");
            str.Append("        <category id=\"c494-1dde-e741-c578\" name=\"Allegiance\" entryId=\"2841-67b5-15d0-8908\" primary=\"false\"/>");
            str.Append("      </categories>");
            str.Append("    </force>");
            str.Append("  </forces>");
            str.Append("</roster>");

            return str.ToString();
        }
    }
}
